
/*CREATE DATABASE db_analysis_20201203;*/

USE db_analysis_20201203;

DROP TABLE IF EXISTS db_analysis_20201203.shoes_product_one;
CREATE TABLE db_analysis_20201203.shoes_product_one (
  product_id int(11) NOT NULL,
  model varchar(64) NOT NULL,
  sku varchar(64) NOT NULL,
  upc varchar(12) NOT NULL,
  ean varchar(14) NOT NULL,
  jan varchar(13) NOT NULL,
  isbn varchar(17) NOT NULL,
  mpn varchar(64) NOT NULL,
  location varchar(128) NOT NULL,
  quantity int(4) NOT NULL DEFAULT '0',
  stock_status_id int(11) NOT NULL,
  image varchar(255) DEFAULT NULL,
  manufacturer_id int(11) NOT NULL,
  shipping tinyint(1) NOT NULL DEFAULT '1',
  price decimal(15,4) NOT NULL DEFAULT '0.0000',
  points int(8) NOT NULL DEFAULT '0',
  tax_class_id int(11) NOT NULL,
  date_available date NOT NULL,
  weight decimal(15,8) NOT NULL DEFAULT '0.00000000',
  weight_class_id int(11) NOT NULL DEFAULT '0',
  length decimal(15,8) NOT NULL DEFAULT '0.00000000',
  width decimal(15,8) NOT NULL DEFAULT '0.00000000',
  height decimal(15,8) NOT NULL DEFAULT '0.00000000',
  length_class_id int(11) NOT NULL DEFAULT '0',
  subtract tinyint(1) NOT NULL DEFAULT '1',
  minimum int(11) NOT NULL DEFAULT '1',
  sort_order int(11) NOT NULL DEFAULT '0',
  status tinyint(1) NOT NULL DEFAULT '0',
  viewed int(5) NOT NULL DEFAULT '0',
  date_added datetime NOT NULL,
  date_modified datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS db_analysis_20201203.shoes_product_two;
CREATE TABLE db_analysis_20201203.shoes_product_two (
  product_id int(11) NOT NULL,
  model varchar(64) NOT NULL,
  sku varchar(64) NOT NULL,
  upc varchar(12) NOT NULL,
  ean varchar(14) NOT NULL,
  jan varchar(13) NOT NULL,
  isbn varchar(17) NOT NULL,
  mpn varchar(64) NOT NULL,
  location varchar(128) NOT NULL,
  quantity int(4) NOT NULL DEFAULT '0',
  stock_status_id int(11) NOT NULL,
  image varchar(255) DEFAULT NULL,
  manufacturer_id int(11) NOT NULL,
  shipping tinyint(1) NOT NULL DEFAULT '1',
  price decimal(15,4) NOT NULL DEFAULT '0.0000',
  points int(8) NOT NULL DEFAULT '0',
  tax_class_id int(11) NOT NULL,
  date_available date NOT NULL,
  weight decimal(15,8) NOT NULL DEFAULT '0.00000000',
  weight_class_id int(11) NOT NULL DEFAULT '0',
  length decimal(15,8) NOT NULL DEFAULT '0.00000000',
  width decimal(15,8) NOT NULL DEFAULT '0.00000000',
  height decimal(15,8) NOT NULL DEFAULT '0.00000000',
  length_class_id int(11) NOT NULL DEFAULT '0',
  subtract tinyint(1) NOT NULL DEFAULT '1',
  minimum int(11) NOT NULL DEFAULT '1',
  sort_order int(11) NOT NULL DEFAULT '0',
  status tinyint(1) NOT NULL DEFAULT '0',
  viewed int(5) NOT NULL DEFAULT '0',
  date_added datetime NOT NULL,
  date_modified datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS db_analysis_20201203.shoes_product_both;
CREATE TABLE db_analysis_20201203.shoes_product_both (
  source varchar(64) NOT NULL,
  product_id int(11) NOT NULL,
  model varchar(64) NOT NULL,
  sku varchar(64) NOT NULL,
  upc varchar(12) NOT NULL,
  ean varchar(14) NOT NULL,
  jan varchar(13) NOT NULL,
  isbn varchar(17) NOT NULL,
  mpn varchar(64) NOT NULL,
  location varchar(128) NOT NULL,
  quantity int(4) NOT NULL DEFAULT '0',
  stock_status_id int(11) NOT NULL,
  image varchar(255) DEFAULT NULL,
  manufacturer_id int(11) NOT NULL,
  shipping tinyint(1) NOT NULL DEFAULT '1',
  price decimal(15,4) NOT NULL DEFAULT '0.0000',
  points int(8) NOT NULL DEFAULT '0',
  tax_class_id int(11) NOT NULL,
  date_available date NOT NULL,
  weight decimal(15,8) NOT NULL DEFAULT '0.00000000',
  weight_class_id int(11) NOT NULL DEFAULT '0',
  length decimal(15,8) NOT NULL DEFAULT '0.00000000',
  width decimal(15,8) NOT NULL DEFAULT '0.00000000',
  height decimal(15,8) NOT NULL DEFAULT '0.00000000',
  length_class_id int(11) NOT NULL DEFAULT '0',
  subtract tinyint(1) NOT NULL DEFAULT '1',
  minimum int(11) NOT NULL DEFAULT '1',
  sort_order int(11) NOT NULL DEFAULT '0',
  status tinyint(1) NOT NULL DEFAULT '0',
  viewed int(5) NOT NULL DEFAULT '0',
  date_added datetime NOT NULL,
  date_modified datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


INSERT INTO db_analysis_20201203.shoes_product_one (
  product_id,
  model,
  sku,
  upc,
  ean,
  jan,
  isbn,
  mpn,
  location,
  quantity,
  stock_status_id,
  image,
  manufacturer_id,
  shipping,
  price,
  points,
  tax_class_id,
  date_available,
  weight,
  weight_class_id,
  length,
  width,
  height,
  length_class_id,
  subtract,
  minimum,
  sort_order,
  status,
  viewed,
  date_added,
  date_modified )
SELECT 
  p.product_id,
  p.model,
  p.sku,
  p.upc,
  p.ean,
  p.jan,
  p.isbn,
  p.mpn,
  p.location,
  p.quantity,
  p.stock_status_id,
  p.image,
  p.manufacturer_id,
  p.shipping,
  p.price,
  p.points,
  p.tax_class_id,
  p.date_available,
  p.weight,
  p.weight_class_id,
  p.length,
  p.width,
  p.height,
  p.length_class_id,
  p.subtract,
  p.minimum,
  p.sort_order,
  p.status,
  p.viewed,
  p.date_added,
  p.date_modified 
FROM db_shoes_afterSeptUpload.shoes_product As p;

INSERT INTO db_analysis_20201203.shoes_product_two (
  product_id,
  model,
  sku,
  upc,
  ean,
  jan,
  isbn,
  mpn,
  location,
  quantity,
  stock_status_id,
  image,
  manufacturer_id,
  shipping,
  price,
  points,
  tax_class_id,
  date_available,
  weight,
  weight_class_id,
  length,
  width,
  height,
  length_class_id,
  subtract,
  minimum,
  sort_order,
  status,
  viewed,
  date_added,
  date_modified )
SELECT 
  p.product_id,
  p.model,
  p.sku,
  p.upc,
  p.ean,
  p.jan,
  p.isbn,
  p.mpn,
  p.location,
  p.quantity,
  p.stock_status_id,
  p.image,
  p.manufacturer_id,
  p.shipping,
  p.price,
  p.points,
  p.tax_class_id,
  p.date_available,
  p.weight,
  p.weight_class_id,
  p.length,
  p.width,
  p.height,
  p.length_class_id,
  p.subtract,
  p.minimum,
  p.sort_order,
  p.status,
  p.viewed,
  p.date_added,
  p.date_modified 
FROM db_shoes_afterNovUpload.shoes_product As p;

INSERT INTO db_analysis_20201203.shoes_product_both (
  source,
  product_id,
  model,
  sku,
  upc,
  ean,
  jan,
  isbn,
  mpn,
  location,
  quantity,
  stock_status_id,
  image,
  manufacturer_id,
  shipping,
  price,
  points,
  tax_class_id,
  date_available,
  weight,
  weight_class_id,
  length,
  width,
  height,
  length_class_id,
  subtract,
  minimum,
  sort_order,
  status,
  viewed,
  date_added,
  date_modified )
SELECT 
  'one',
  p.product_id,
  p.model,
  p.sku,
  p.upc,
  p.ean,
  p.jan,
  p.isbn,
  p.mpn,
  p.location,
  p.quantity,
  p.stock_status_id,
  p.image,
  p.manufacturer_id,
  p.shipping,
  p.price,
  p.points,
  p.tax_class_id,
  p.date_available,
  p.weight,
  p.weight_class_id,
  p.length,
  p.width,
  p.height,
  p.length_class_id,
  p.subtract,
  p.minimum,
  p.sort_order,
  p.status,
  p.viewed,
  p.date_added,
  p.date_modified 
FROM db_shoes_afterSeptUpload.shoes_product As p;

INSERT INTO db_analysis_20201203.shoes_product_both (
  source,
  product_id,
  model,
  sku,
  upc,
  ean,
  jan,
  isbn,
  mpn,
  location,
  quantity,
  stock_status_id,
  image,
  manufacturer_id,
  shipping,
  price,
  points,
  tax_class_id,
  date_available,
  weight,
  weight_class_id,
  length,
  width,
  height,
  length_class_id,
  subtract,
  minimum,
  sort_order,
  status,
  viewed,
  date_added,
  date_modified )
SELECT 
  'two',
  p.product_id,
  p.model,
  p.sku,
  p.upc,
  p.ean,
  p.jan,
  p.isbn,
  p.mpn,
  p.location,
  p.quantity,
  p.stock_status_id,
  p.image,
  p.manufacturer_id,
  p.shipping,
  p.price,
  p.points,
  p.tax_class_id,
  p.date_available,
  p.weight,
  p.weight_class_id,
  p.length,
  p.width,
  p.height,
  p.length_class_id,
  p.subtract,
  p.minimum,
  p.sort_order,
  p.status,
  p.viewed,
  p.date_added,
  p.date_modified 
FROM db_shoes_afterNovUpload.shoes_product As p;








