
DROP TABLE IF EXISTS db_settings.data_correction_sizes;

CREATE TABLE db_settings.data_correction_sizes (
    dcs_id INT AUTO_INCREMENT PRIMARY KEY,
    dcs_type VARCHAR(255) NOT NULL default '', 
    dcs_orig VARCHAR(255) NOT NULL default '', 
    dcs_new VARCHAR(255) NOT NULL default '');



INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 20', 'EU 20');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 21', 'EU 21');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 22', 'EU 22');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 23', 'EU 23');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 24', 'EU 24');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 25', 'EU 25');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 26', 'EU 26');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 27', 'EU 27');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 28', 'EU 28');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 29', 'EU 29');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 30', 'EU 30');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 31', 'EU 31');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 32', 'EU 32');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 33', 'EU 33');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 34', 'EU 34');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 35', 'EU 35');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 36', 'EU 36');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 36.5', 'EU 36.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 37', 'EU 37');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 37.5', 'EU 37.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 38', 'EU 38');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 38.5', 'EU 38.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 39', 'EU 39');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 39.5', 'EU 39.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 40', 'EU 40');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 40.5', 'EU 40.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 41', 'EU 41');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 41.5', 'EU 41.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 42', 'EU 42');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 42.5', 'EU 42.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 43', 'EU 43');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 44', 'EU 44');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 44.5', 'EU 44.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 45', 'EU 45');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 45.5', 'EU 45.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 46', 'EU 46');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','EU 46.5', 'EU 46.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 10', 'UK 10.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 10.0', 'UK 10.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 10.5', 'UK 10.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 11', 'UK 11.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 11.0', 'UK 11.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 11.5', 'UK 11.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 12', 'UK 12.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 12.0', 'UK 12.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 12.5', 'UK 12.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 13', 'UK 13.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 13.0', 'UK 13.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 13.5', 'UK 13.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 14', 'UK 14.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 14.0', 'UK 14.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 14.5', 'UK 14.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 3.5', 'UK 3.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 4.0', 'UK 4.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 4.5', 'UK 4.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 5', 'UK 5.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 5.0', 'UK 5.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 5.5', 'UK 5.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 6', 'UK 6.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 6.0', 'UK 6.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 6.5', 'UK 6.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 7', 'UK 7.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 7.0', 'UK 7.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 7.5', 'UK 7.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 8', 'UK 8.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 8.0', 'UK 8.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 8.5', 'UK 8.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 9', 'UK 9.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 9.0', 'UK 9.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','UK 9.5', 'UK 9.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 10', 'US 10.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 10.0', 'US 10.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 10.5', 'US 10.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 11', 'US 11.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 11.0', 'US 11.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 11.5', 'US 11.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 12', 'US 12.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 12.0', 'US 12.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 12.5', 'US 12.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 13', 'US 13.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 13.0', 'US 13.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 13.5', 'US 13.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 14', 'US 14.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 14.0', 'US 14.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 14.5', 'US 14.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 4', 'US 4.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 4.0', 'US 4.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 4.5', 'US 4.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 5', 'US 5.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 5.0', 'US 5.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 5.5', 'US 5.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 6', 'US 6.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 6.0', 'US 6.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 6.5', 'US 6.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 7', 'US 7.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 7.0', 'US 7.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 7.5', 'US 7.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 8', 'US 8.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 8.0', 'US 8.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 8.5', 'US 8.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 9', 'US 9.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 9.0', 'US 9.0');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','US 9.5', 'US 9.5');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','XXXL', 'XXXL');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','XXL', 'XXL');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','XL', 'XL');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','L', 'L');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','M', 'M');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','S', 'S');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','XS', 'XS');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','XXS', 'XXS');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','XXXS', 'XXXS');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','24', '24');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','25', '25');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','26', '26');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','27', '27');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','28', '28');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','29', '29');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','30', '30');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','31', '31');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','32', '32');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','33', '33');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','34', '34');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','35', '35');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','36', '36');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','37', '37');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','38', '38');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','39', '39');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','40', '40');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','41', '41');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','42', '42');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','43', '43');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','44', '44');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','45', '45');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','46', '46');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','48', '48');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','50', '50');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','52', '52');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','54', '54');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','56', '56');
INSERT INTO db_settings.data_correction_sizes (dcs_type, dcs_orig, dcs_new) VALUES ('shoe sizes','58', '58');

